# Site settings
description: Anteckningar, idéer och arbetalog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hugo Hoover
user_description: JAg är en far, intresserad av  proteinstrukturer, biomolekylär interaktioner, data science och språk.
user_title:
email: hugohoover.denovo@gmail.com
twitter_username: huWANGplus
github_username: hugohoover
gplus_username:
disqus_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

future: true
